# Generated by Django 3.0.7 on 2020-06-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='photo')),
            ],
        ),
    ]
