# Generated by Django 3.0.7 on 2020-06-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20200612_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=1000)),
            ],
        ),
    ]
